[package]
name = "ytpl"
version = "0.1.0"
authors = ["orhun <orhunparmaksiz@gmail.com>"]
edition = "2018"

[dependencies]
configparser = "2.0.0"
anyhow = "1.0.37"
youtube_dl = "0.6.0"
git2 = "0.13.15"
chrono = "0.4.19"
